steps:
  - name: node:8
    args: ['yarn', 'install']

  - name: node:8
    args: ['yarn', 'test-ci']

  # TODO: cache node_modules

  - name: elixir:1.7
    args: ['mix', 'format', '--check-formatted']
    dir: 'backend'

  - name: elixir:1.7
    args: ['mix', 'test']
    dir: 'backend'
