steps:
  # install JS dependencies
  - name: node:10
    args: ['yarn', 'install']

  # test JS client
  - name: node:10
    args: ['yarn', 'test-ci']

  # TODO: cache node_modules

  # check Elixir formatting
  - name: elixir:1.7
    args: ['mix', 'format', '--check-formatted']
    dir: 'backend'
    waitFor: ['-']  # the '-' indicates that this step begins immediately

  # install Hex
  - name: elixir:1.7
    args: ['mix', 'local.hex', '--force']
    dir: 'backend'
    waitFor: ['-']  # the '-' indicates that this step begins immediately

  - name: elixir:1.7
    args: ['mix', 'local.rebar', '--force']
    dir: 'backend'
    waitFor: ['-']  # the '-' indicates that this step begins immediately

  # TODO: create custom Dockerfile to skip all this (^^)

  # install dependencies
  - name: elixir:1.7
    args: ['mix', 'deps.get']
    dir: 'backend'

  # test Elixir application
  - name: elixir:1.7
    args: ['mix', 'test']
    dir: 'backend'

# TODO: mix credo
