# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/labs/tree/master/developer-tools/nodejs/porting
version: '3.7'

services:
  graphql-api:
    build: ./packages/api
    image: adeira/quick-payments-api
#    overwrites CMD from Dockerfile
#    command: ["yarn", "development"]
    ports:
      - target: 3000
        published: 80
    volumes:
#      - ./packages/api:/app
#     HOST:CONTAINER
      - '.:/app' # add everything because of workspaces and dependency hoisting (FIXME)
